### ISSUE TITLE
[Bug] Missing settings data

### ISSUE THREAD

**Issue by danielvistisen** [jammin411/MatchmakingMonitor#16]
No sure how but it no longer there. I assume its due to an update and this clickonce is setup to auto update?

Everything is set to 0 resulting in everyone getting super-unicom color.

**Comment by siegerx3** [comment]
When did it happen? By updating from 1.0.3.0 to 1.0.4.0 ?

**Comment by siegerx3** [comment]
I also received 2 bug reports from the website with the same issue but i can't replicate it.

**Comment by siegerx3** [comment]
Also what do you mean with "clickonce is setup to auto update" ?

**Comment by Termx** [comment]
siegerx3, I was able to reproduce this earlier today. But it wasn't the program itself, but the "warships.today" site. It was having problems for many hours earlier today, the home page unable to load due to their web server hanging up on request. I haven't took the time to analyze your program code, but if you do make a call to collect data from that site...it could explain why everything was showing as "0" when the site was down earlier.

The site is back online now, so this issue is no longer reproducing. Also, if you do collect data from the site, then it maybe best to add a notification if the request fails so the user is aware what the problem is.

**Comment by siegerx3** [comment]
Damn. That's what i thought. I think i have a better idea. I will put the logic that calculates the values on my server and change the call from the app to go to my server instead of directly warships.today.

Then i'll cache the stats daily or every two days. So when warships.today is down i will still have my cached version.

**Comment by siegerx3** [comment]
Oh, and thanks for the information @Termx :)

**Comment by siegerx3** [comment]
#17 Also made me aware of this bug lol

**Comment by Termx** [comment]
No problem o7

**Comment by danielvistisen** [comment]
Regarding clickonce: I didn't update the app manually. So figured that might be the reason. A new version. Can't find version number inside tha app. Checked the .application file. Its not set to auto update. So update wasn't the reason.

**Comment by siegerx3** [comment]
I have never read "clickonce" though^^ .application file? You mean the exe?
