### ISSUE TITLE
Matchmaking Monitor suddenly stopped working today

### ISSUE THREAD

**Issue by Corsair-I** [jammin411/MatchmakingMonitor#61]
MMM suddenly stopped working today for me. I reinstalled 1.2.0.4 as someone suggested but it did not help.

**Comment by Corsair-I** [comment]
I found what it was. The new Aslain mod put the replays in subfolders and the MMM cannot find them. I have no clue why replays are needed for the MMM to work.

**Comment by stewieoO** [comment]
Because there is a temporary file in the replays folder that contains various information about the match as soon as you enter the loadscreen. That's where the monitor get's all that it needs.

You can join my discord https://discord.gg/Tds7WBs and try the new version i am working on, which is working with the subfolders aswell :)
